version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DATABASE: 'MDS12'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'password'

  test-db:
    image: postgres:15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DATABASE: 'MDS12'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'password'